// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friendship.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendEvent = `-- name: CreateFriendEvent :one
INSERT INTO friend_event (friendship_id, actor_id, type)
VALUES ($1, $2, $3)
RETURNING id, friendship_id, actor_id, type, created_at
`

type CreateFriendEventParams struct {
	FriendshipID pgtype.UUID
	ActorID      pgtype.UUID
	Type         string
}

func (q *Queries) CreateFriendEvent(ctx context.Context, arg CreateFriendEventParams) (FriendEvent, error) {
	row := q.db.QueryRow(ctx, createFriendEvent, arg.FriendshipID, arg.ActorID, arg.Type)
	var i FriendEvent
	err := row.Scan(
		&i.ID,
		&i.FriendshipID,
		&i.ActorID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :one
INSERT INTO friendship (user_a, user_b, status, status_actor_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_a, user_b, status, status_actor_id, created_at, updated_at
`

type CreateFriendshipParams struct {
	UserA         pgtype.UUID
	UserB         pgtype.UUID
	Status        string
	StatusActorID pgtype.UUID
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendship,
		arg.UserA,
		arg.UserB,
		arg.Status,
		arg.StatusActorID,
	)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM friendship
WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFriendshipByPair = `-- name: GetFriendshipByPair :one
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM friendship
WHERE user_a = $1 AND user_b = $2
`

type GetFriendshipByPairParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByPair, arg.UserA, arg.UserB)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsForFriendship = `-- name: ListEventsForFriendship :many
SELECT id, friendship_id, actor_id, type, created_at FROM friend_event
WHERE friendship_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventsForFriendship(ctx context.Context, friendshipID pgtype.UUID) ([]FriendEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForFriendship, friendshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendEvent
	for rows.Next() {
		var i FriendEvent
		if err := rows.Scan(
			&i.ID,
			&i.FriendshipID,
			&i.ActorID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriendshipsForUser = `-- name: ListFriendshipsForUser :many
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM friendship
WHERE (user_a = $1 OR user_b = $1)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY updated_at DESC
`

type ListFriendshipsForUserParams struct {
	UserA  pgtype.UUID
	Status pgtype.Text
}

func (q *Queries) ListFriendshipsForUser(ctx context.Context, arg ListFriendshipsForUserParams) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listFriendshipsForUser, arg.UserA, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Friendship
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(
			&i.ID,
			&i.UserA,
			&i.UserB,
			&i.Status,
			&i.StatusActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFriendshipStatus = `-- name: UpdateFriendshipStatus :one
UPDATE friendship
SET status = $2, status_actor_id = $3
WHERE id = $1
RETURNING id, user_a, user_b, status, status_actor_id, created_at, updated_at
`

type UpdateFriendshipStatusParams struct {
	ID            pgtype.UUID
	Status        string
	StatusActorID pgtype.UUID
}

func (q *Queries) UpdateFriendshipStatus(ctx context.Context, arg UpdateFriendshipStatusParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, updateFriendshipStatus, arg.ID, arg.Status, arg.StatusActorID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
