// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type FriendEvent struct {
	ID           pgtype.UUID
	FriendshipID pgtype.UUID
	ActorID      pgtype.UUID
	Type         string
	CreatedAt    pgtype.Timestamptz
}

type Friendship struct {
	ID            pgtype.UUID
	UserA         pgtype.UUID
	UserB         pgtype.UUID
	Status        string
	StatusActorID pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID          pgtype.UUID
	AuthSubject string
	CreatedAt   pgtype.Timestamptz
}
