// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPersona = `-- name: CreatePersona :one
INSERT INTO persona (id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreatePersona(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPersona, id)
	err := row.Scan(&id)
	return id, err
}
