// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: relationship.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFriendEvent = `-- name: CreateFriendEvent :one
INSERT INTO friend_event (relationship_id, actor_id, type)
VALUES ($1, $2, $3)
RETURNING id, relationship_id, actor_id, type, created_at
`

type CreateFriendEventParams struct {
	RelationshipID pgtype.UUID
	ActorID        pgtype.UUID
	Type           string
}

func (q *Queries) CreateFriendEvent(ctx context.Context, arg CreateFriendEventParams) (FriendEvent, error) {
	row := q.db.QueryRow(ctx, createFriendEvent, arg.RelationshipID, arg.ActorID, arg.Type)
	var i FriendEvent
	err := row.Scan(
		&i.ID,
		&i.RelationshipID,
		&i.ActorID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createRelationship = `-- name: CreateRelationship :one
INSERT INTO relationship (user_a, user_b, status, status_actor_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_a, user_b, status, status_actor_id, created_at, updated_at
`

type CreateRelationshipParams struct {
	UserA         pgtype.UUID
	UserB         pgtype.UUID
	Status        string
	StatusActorID pgtype.UUID
}

func (q *Queries) CreateRelationship(ctx context.Context, arg CreateRelationshipParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, createRelationship,
		arg.UserA,
		arg.UserB,
		arg.Status,
		arg.StatusActorID,
	)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationshipByID = `-- name: GetRelationshipByID :one
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM relationship
WHERE id = $1
`

func (q *Queries) GetRelationshipByID(ctx context.Context, id pgtype.UUID) (Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationshipByID, id)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelationshipByPair = `-- name: GetRelationshipByPair :one
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM relationship
WHERE user_a = $1 AND user_b = $2
`

type GetRelationshipByPairParams struct {
	UserA pgtype.UUID
	UserB pgtype.UUID
}

func (q *Queries) GetRelationshipByPair(ctx context.Context, arg GetRelationshipByPairParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, getRelationshipByPair, arg.UserA, arg.UserB)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEventsForRelationship = `-- name: ListEventsForRelationship :many
SELECT id, relationship_id, actor_id, type, created_at FROM friend_event
WHERE relationship_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventsForRelationship(ctx context.Context, relationshipID pgtype.UUID) ([]FriendEvent, error) {
	rows, err := q.db.Query(ctx, listEventsForRelationship, relationshipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FriendEvent
	for rows.Next() {
		var i FriendEvent
		if err := rows.Scan(
			&i.ID,
			&i.RelationshipID,
			&i.ActorID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationshipsForUser = `-- name: ListRelationshipsForUser :many
SELECT id, user_a, user_b, status, status_actor_id, created_at, updated_at FROM relationship
WHERE (user_a = $1 OR user_b = $1)
  AND ($2::text IS NULL OR status = $2::text)
ORDER BY updated_at DESC
`

type ListRelationshipsForUserParams struct {
	UserA  pgtype.UUID
	Status pgtype.Text
}

func (q *Queries) ListRelationshipsForUser(ctx context.Context, arg ListRelationshipsForUserParams) ([]Relationship, error) {
	rows, err := q.db.Query(ctx, listRelationshipsForUser, arg.UserA, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relationship
	for rows.Next() {
		var i Relationship
		if err := rows.Scan(
			&i.ID,
			&i.UserA,
			&i.UserB,
			&i.Status,
			&i.StatusActorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelationshipStatus = `-- name: UpdateRelationshipStatus :one
UPDATE relationship
SET status = $2, status_actor_id = $3
WHERE id = $1
RETURNING id, user_a, user_b, status, status_actor_id, created_at, updated_at
`

type UpdateRelationshipStatusParams struct {
	ID            pgtype.UUID
	Status        string
	StatusActorID pgtype.UUID
}

func (q *Queries) UpdateRelationshipStatus(ctx context.Context, arg UpdateRelationshipStatusParams) (Relationship, error) {
	row := q.db.QueryRow(ctx, updateRelationshipStatus, arg.ID, arg.Status, arg.StatusActorID)
	var i Relationship
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.StatusActorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
