// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO "user" (auth_subject)
VALUES ($1)
RETURNING id, auth_subject, created_at
`

func (q *Queries) CreateUser(ctx context.Context, authSubject string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, authSubject)
	var i User
	err := row.Scan(&i.ID, &i.AuthSubject, &i.CreatedAt)
	return i, err
}

const getUserByAuthSubject = `-- name: GetUserByAuthSubject :one
SELECT id, auth_subject, created_at FROM "user"
WHERE auth_subject = $1
`

func (q *Queries) GetUserByAuthSubject(ctx context.Context, authSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByAuthSubject, authSubject)
	var i User
	err := row.Scan(&i.ID, &i.AuthSubject, &i.CreatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, auth_subject, created_at FROM "user"
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(&i.ID, &i.AuthSubject, &i.CreatedAt)
	return i, err
}
