// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fair-n-square-co/core/internal/ledger/service (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository.go -package=mocks . Repository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/fair-n-square-co/core/internal/ledger/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ListFriendshipsForUser mocks base method.
func (m *MockRepository) ListFriendshipsForUser(ctx context.Context, userID string) ([]repository.Friendship, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFriendshipsForUser", ctx, userID)
	ret0, _ := ret[0].([]repository.Friendship)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFriendshipsForUser indicates an expected call of ListFriendshipsForUser.
func (mr *MockRepositoryMockRecorder) ListFriendshipsForUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFriendshipsForUser", reflect.TypeOf((*MockRepository)(nil).ListFriendshipsForUser), ctx, userID)
}
